### ISSUE TITLE
Newtonsoft.Json.JsonReaderException: 'Unexpected end of content while loading JObject. Path 'BidPrice', line 1, position 40.'

### ISSUE THREAD

**Issue by MrGekko1** [QANTau/DTC-Client#1]
When I subscribe to F.US.GCEZ20 data after a while I get errors like below at QUANT.DTC.Utils.GetMessageType Line 15:

"Newtonsoft.Json.JsonReaderException: 'Unexpected end of content while loading JObject. Path 'BidPrice', line 1, position 40.'"

The recieved string is "{\"Type\":117,\"SymbolID\":1,\"BidPrice\":1891".

**Comment by QANTau** [comment]
Hi ... I don't have the ability to test on that symbol but I have added a try ... catch into that section of the code in an effort to gather more information.  If you are still trying to get this one to work and it fails again, can you grab the value of "msg" if the code stops on the debugger step please.  I'll close this issue but feel free to re-open.
