### ISSUE TITLE
How did you implement the protobuf for the SC DTC?

### ISSUE THREAD

**Issue by eabase** [QANTau/DTC-Client#2]
The DTC has changed since 2018, so we need to update that, if that's what you're using here.

How did you compile and implement the protobuf for the SC DTC?

**Comment by QANTau** [comment]
I've just re-tested the client with the latest version of SC and the methods that I have available for testing in the UI are still using the same protocol specification as the current documentation.  It's possibly that there have been changes to some of the methods that aren't implemented in this project.

I didn't implement protobuf for this project - the messages are built as native C# code in the DTC project (see Messages for how this is done).
